SOURCE starter/answers.sql;

SHOW TABLES LIKE 'Student';

DESCRIBE Student;

SELECT
COLUMN_NAME,
DATA_TYPE,
IS_NULLABLE,
COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='assignmentdb'
AND TABLE_NAME='Student'
ORDER BY ORDINAL_POSITION;

SHOW CREATE TABLE Student;
